[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python upload_app.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
PORT = "8000"
UPLOAD_TOKEN = "${{RAILWAY_UPLOAD_TOKEN}}"